//
//  KMGlobalResourceDefine.h
//  KnowMeApp
//
//  Created by huixiubao on 16/6/30.
//  Copyright © 2016年 baidu. All rights reserved.
//

#ifndef KMGlobalResourceDefine_h
#define KMGlobalResourceDefine_h


// 九宫格拉伸参数
#define	STRETCH_IMAGE_WITH_LEFT_CAPWIDTH_0				0.0f
#define	STRETCH_IMAGE_WITH_LEFT_CAPWIDTH_1              1.0f
#define	STRETCH_IMAGE_WITH_LEFT_CAPWIDTH_2				2.0f
#define	STRETCH_IMAGE_WITH_LEFT_CAPWIDTH_3				3.0f
#define	STRETCH_IMAGE_WITH_LEFT_CAPWIDTH_4				4.0f
#define	STRETCH_IMAGE_WITH_LEFT_CAPWIDTH_5				5.0f
#define	STRETCH_IMAGE_WITH_LEFT_CAPWIDTH_6				6.0f
#define	STRETCH_IMAGE_WITH_LEFT_CAPWIDTH_10				10.0f
#define	STRETCH_IMAGE_WITH_LEFT_CAPWIDTH_12				12.0f
#define	STRETCH_IMAGE_WITH_LEFT_CAPWIDTH_13				13.0f
#define	STRETCH_IMAGE_WITH_LEFT_CAPWIDTH_15				15.0f
#define	STRETCH_IMAGE_WITH_LEFT_CAPWIDTH_20				20.0f

#define	STRETCH_IMAGE_WITH_TOP_CAPHEIGHT_0				0.0f
#define	STRETCH_IMAGE_WITH_TOP_CAPHEIGHT_1				1.0f
#define	STRETCH_IMAGE_WITH_TOP_CAPHEIGHT_2				2.0f
#define	STRETCH_IMAGE_WITH_TOP_CAPHEIGHT_3				3.0f
#define	STRETCH_IMAGE_WITH_TOP_CAPHEIGHT_4				4.0f
#define	STRETCH_IMAGE_WITH_TOP_CAPHEIGHT_5				5.0f
#define	STRETCH_IMAGE_WITH_TOP_CAPHEIGHT_6				6.0f
#define	STRETCH_IMAGE_WITH_TOP_CAPHEIGHT_10				10.0f
#define	STRETCH_IMAGE_WITH_TOP_CAPHEIGHT_12				12.0f
#define	STRETCH_IMAGE_WITH_TOP_CAPHEIGHT_15				15.0f
#define	STRETCH_IMAGE_WITH_TOP_CAPHEIGHT_45				45.0f
#define	STRETCH_IMAGE_WITH_TOP_CAPHEIGHT_50				50.0f
#define	STRETCH_IMAGE_WITH_TOP_CAPHEIGHT_75				75.0f


#endif /* KMGlobalResourceDefine_h */
